@ImYourSouffleur.Server_HostAddress = http://localhost:5053

GET {{ImYourSouffleur.Server_HostAddress}}/api/customer/12345
Accept: application/json

###

GET {{ImYourSouffleur.Server_HostAddress}}/api/appointments?persona=Sales
Accept: application/json

###

GET {{ImYourSouffleur.Server_HostAddress}}/api/report
Accept: text/plain

### 



POST {{ImYourSouffleur.Server_HostAddress}}/api/report?connectionId=YourConnectionIdHere
Content-Type: application/json

{
  "content": "J'ai réparer la machine de Mr Durant",
  "customerInfo": "Mr Durant avec comme email f@toto.fr"  
}